version: "3.3"
services:

  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 hello:app --reload
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root

  cache:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: